version: "3.5"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"

  books:
    image: "books_server:latest"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mongo

